name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Set working directory
        run: cd app  # 원하는 작업 디렉토리로 이동합니다.
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: realcold0/node-express
          stage: main
          yaml: |
            name: node-express
            app: node@18
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: ${{ secrets.PORT }}
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                - name: DB_USER
                  value: ${{ secrets.DB_USER }}
                - name: DB_PSWORD
                  value: ${{ secrets.DB_PSWORD }}
                - name: DB_DATABASE
                  value: ${{ secrets.DB_DATABASE }}
                - name: SECRET_ACCESS_KEY
                  value: ${{ secrets.SECRET_ACCESS_KEY }}
                - name: SECRET_REFRESH_KEY
                  value: ${{ secrets.SECRET_REFRESH_KEY }}
                - name: SERVER_HOST
                  value: ${{ secrets.SERVER_HOST }}
                - name : SSL_KEY
                  value: ${{ secrets.SSL_KEY }}
                - name : SSL_CERT
                  value: ${{ secrets.SSL_CERT }}
              ports:
                - "3000:3000"
                - "443:443"
              install: npm ci --production
              start: npm start
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
                path: app
              preset: node
